= Elastic Observability for AWS

:imagesdir: images/

This application allows you to practice how to use https://www.elastic.co/observability[Elastic Observability] to monitor services from AWS. It has been built using principles of data streaming using https://kafka.apache.org[Apache Kafka]. Built around the Pac-Man game this application ingest and store events from the game into Kafka topics and processes them in near real-time using https://ksqldb.io/[ksqlDB]. In order to keep you focused in the application details this project is based on several fully managed services from AWS such as https://aws.amazon.com/msk[Managed Streaming for Apache Kafka], https://aws.amazon.com/elasticache/redis[ElastiCache for Redis], and https://aws.amazon.com/ecs[Elastic Container Service] that does the infrastructure heavy lifting for you.

== What you are going to need?

* *Terraform* - The application is automatically created using https://www.terraform.io[Terraform]. Besides having Terraform installed locally, you will need to provide your AWS credentials so Terraform can create and manage the resources for you.

* *Java and Maven* - Three APIs will be created and are backed by Lambda functions written in https://openjdk.java.net/[Java], therefore you will need to have Java 11+ installed to build the source-code. The build itseld is implemented using https://maven.apache.org/[Maven], and it is triggered automatically by Terraform.

== Deploying the application

1. Enter the folder that contains the AWS code
+
[source,bash]
----
cd terraform/aws
----

2. Initialize the Terraform plugins
+
[source,bash]
----
terraform init
----

3. Start the application deployment
+
[source,bash]
----
terraform apply
----

4. Output with endpoints will be shown
+
[source,bash]
----
Outputs:

Pacman = http://<UNIQUE_NAME>.s3-website-region.amazonaws.com
----

*Note:* When you are done with the application, you can automatically destroy all the resources created by Terraform using the command below:

[source,bash]
----
terraform destroy
----

== License

This project is licensed under the link:LICENSE[Apache 2.0 License.]
